#pragma once

#include "CAMLOC_SHAPE_OFFSET_TYPE.generated.h"

UENUM(BlueprintType)
enum CAMLOC_SHAPE_OFFSET_TYPE {
    CAMLOC_SHAPE_OFFSET_TYPE_NONE,
    CAMLOC_SHAPE_OFFSET_TYPE_SPHERE,
    CAMLOC_SHAPE_OFFSET_TYPE_CYLINDER,
};

