#pragma once

#include "KazumiTigerAnimTypes.generated.h"

UENUM(BlueprintType)
enum KazumiTigerAnimTypes {
    TIGER_ANIM_S01,
    TIGER_ANIM_W01,
    TIGER_ANIM_KZM_SPSTART,
    TIGER_ANIM_ATTACK_00,
    TIGER_ANIM_ATTACK_01,
    TIGER_ANIM_ATTACK_02,
    TIGER_ANIM_MISSILE_00,
    TIGER_ANIM_MISSILE_01,
    TIGER_ANIM_MISSILE_02,
    TIGER_ANIM_MISSILE_03,
    TIGER_ANIM_MISSILE_04,
    TIGER_ANIM_MISSILE_05,
    TIGER_ANIM_THROW_00,
    TIGER_ANIM_THROW_01,
    TIGER_ANIM_THROW_02,
    TIGER_ANIM_THROW_03,
    TIGER_ANIM_THROW_04,
    TIGER_ANIM_EFFECT_00,
    TIGER_ANIM_EFFECT_01,
    TIGER_ANIM_EFFECT_02,
    TIGER_ANIM_EFFECT_03,
    TIGER_ANIM_EFFECT_04,
    TIGER_ANIM_MAX UMETA(Hidden),
};

