#pragma once

#include "MotheadEvent.generated.h"

UENUM(BlueprintType)
enum MotheadEvent {
    MOTEV_START_CLIMAX,
    MOTEV_DEAD_ZAKO,
    MOTEV_CHANGE_IN_ZAKO,
    MOTEV_SWITCH_SECRETLY_STAGE,
    MOTEV_GENERIC_DRAMA_EVENT1,
    MOTEV_GENERIC_DRAMA_EVENT2,
    MOTEV_GENERIC_DRAMA_EVENT3,
    MOTEV_1P_TRANSFORM_NEO_AKUMA,
    MOTEV_2P_TRANSFORM_NEO_AKUMA,
    MOTEV_RAGEARTS_LASTATTACKHIT,
    MOTEV_MAX UMETA(Hidden),
};

